import Images from '../assets/images';
import { Themes } from '../assets/themes';

export const REGEX_SALARY = /[.,-/]/g;
export const staticValue = {
  DEFAULT: 1,
  TIME_IMAGE_LOAD: 500,
};

export const ERRORS = {
  default: 'common.error.unknown',
  network: 'common.error.network',
};
export const listSuggest = [
  'Laptop',
  'Màn hình',
  'PC',
  'Máy tính',
  'RAM',
  'Card',
  'Laptop MSI',
  'Laptop MSI GP65',
  'Laptop MSI GP65 Leopard',
  'Laptop HP Pavilion',
  'Laptop HP',
  'Laptop HP OMEN',
  'Laptop Acer',
  'Laptop Acer Aspire 3',
  'Laptop Acer Aspire 5',
  'Laptop Acer Spin',
  'Laptop Acer Nitro 5',
  'Laptop Lenovo Yoga',
  'Laptop Acer Swift 3',
  'Laptop Acer Swift',
  'Laptop ASUS',
  'Laptop ASUS ZenBook',
  'Laptop ASUS ROG',
  'Laptop ASUS ROG Zephyrus',
  'Laptop Lenovo Ideapad',
  'Màn hình LCD',
  'Màn hình LCD Dell',
  'Màn hình LCD Dell E2220H',
  'Màn hình LCD Dell E2420H',
  'Màn hình LCD Dell S2421H',
  'Màn hình LCD SAMSUNG',
  'Màn hình LCD HP',
  'Màn hình LCD MSI',
  'Màn hình LCD ACER',
  'Màn hình LCD ASUS',
  'Màn hình LCD VIEWSONIC',
  'Màn hình LCD Lenovo',
  'Màn Hình Acer',
  'Màn Hình Dell',
  'Màn Hình Samsung',
  'Màn hình LCD BenQ',
  'PC HP',
  'PC Dell',
  'PC Dell Vostro',
  'PC HP Pavilion',
  'PC INTEL',
  'PC ASUS',
  'Máy tính để bàn',
  'Máy tính để bàn - PC Intel',
  'Máy tính để bàn - PC HP',
  'Máy tính để bàn - PC Acer',
  'PC Acer',
  'PC Acer Aspire',
  'PC Lenovo',
  'RAM desktop',
  'RAM desktop KINGSTON',
  'RAM desktop KINGMAX',
  'RAM desktop G.SKILL',
  'RAM desktop CORSAIR',
  'RAM desktop GeIL',
  'RAM desktop KLEVV BOLT',
  'RAM desktop KLEVV',
  'Card màn hình ASUS',
  'Card màn hình Gigabyte',
  'Card màn hình MSI GeForce',
  'Card màn hình ASUS NVIDIA',
  'Card màn hình MSI',
  'Card màn hình MSI GeForce RTX 3080'


];

export const dataPicker = [
  'label1',
  'label2',
  'label3',
  'label4',
  'label5',
  'label6',
  'label7',
  'label8',
  'label9',
  'label10',
];

export const starImage = [
  Images.star.one,
  Images.star.two,
  Images.star.three,
  Images.star.four,
  Images.star.five,
];
