const AUTHENTICATE_ROUTE = {
  LOGIN: '@AUTHENTICATE_ROUTE/LOGIN',
  REGISTER: '@AUTHENTICATE_ROUTE/REGISTER',
};

const APP_ROUTE = {
  MAIN_TAB: 'MAIN_TAB',
  FLASH_SALE: 'FLASH_SALE',
  SHIPPING_ADDRESS: 'SHIPPING_ADDRESS',
  SEARCH_RESULT: 'SEARCH_RESULT',
};

const HOME_ROUTE = {
  ROOT: 'HOME_ROOT',
  HOME: 'HOME',
  PRODUCT_DETAILS: 'PRODUCT_DETAILS',
};

const EXPLORE_ROUTE = {
  ROOT: 'SETTING_ROOT',
  EXPLORE: 'EXPLORE',
};

const CART_ROUTE = {
  ROOT: 'NOTIFICATION_ROOT',
  CART: 'CART',
  PAYMENT_METHOD: 'PAYMENT_METHOD',
};

const OFFER_ROUTE = {
  ROOT: 'ACCOUNT_ROUTE',
  OFFER: 'OFFER',
};

const ACCOUNT_ROUTE = {
  ROOT: 'HEART_ROUT',
  ACCOUNT: 'ACCOUNT',
  PROFILE: 'PROFILE',
  ADDRESS: 'ADDRESS',
  ADDADDRESS: 'ADDADDRESS',
};

const TAB_NAVIGATION_ROOT = {
  HOME_ROUTE,
  EXPLORE_ROUTE,
  CART_ROUTE,
  OFFER_ROUTE,
  ACCOUNT_ROUTE,
};

export {APP_ROUTE, TAB_NAVIGATION_ROOT, AUTHENTICATE_ROUTE};
